export const currencies = [
  "AFN", "ALL", "DZD", "USD", "EUR", "AOA", "XCD", "ARS", "AMD", "AWG", "AZN", 
  "BSD", "BHD", "BDT", "BBD", "BYN", "BZD", "BMD", "BTN", "BOB", "BRL", "BND", "BGN", "BIF",
  "KHR", "CVE", "XOF", "XAF", "CAD", "CLP", "CNY", "COP", "KMF", "CDF", "CRC", "HRK", "CUP", "CZK",
  "DKK", "DOP",
  "EGP", "ERN", "ETB",
  "FJD",
  "GMD", "GEL", "GHS", "GIP", "GTQ", "GNF", "GYD",
  "HTG", "HNL", "HUF",
  "ISK", "INR", "IDR", "IRR", "IQD", "ILS",
  "JMD", "JPY", "JOD",
  "KZT", "KES", "KWD", "KGS",
  "LAK", "LBP", "LSL", "LRD", "LYD",
  "MOP", "MKD", "MGA", "MWK", "MYR", "MVR", "MRU", "MUR", "MXN", "MDL", "MNT", "MAD", "MZN", "MMK",
  "NAD", "NPR", "ANG", "NZD", "NIO", "NGN", "NOK",
  "OMR",
  "PKR", "PAB", "PYG", "PEN", "PHP", "PLN",
  "QAR",
  "RON", "RUB", "RWF",
  "WST", "STN", "SAR", "RSD", "SCR", "SLL", "SGD", "SBD", "SOS", "ZAR", "KRW", "SSP", "LKR", "SDG", "SRD", "SZL", "SEK", "CHF", "SYP",
  "TWD", "TJS", "TZS", "THB", "TOP", "TTD", "TND", "TRY", "TMT",
  "UGX", "UAH", "AED", "GBP", "UYU", "UZS",
  "VUV", "VES", "VND",
  "YER",
  "ZMW", "ZWL",
];
