import type { User, P2PAd, Trade, TradeChatMessage, SupportTicket, Feedback } from './types';
import { add, sub } from 'date-fns';

const now = new Date();

export const mockUsers: User[] = [
  {
    id: 'user-001',
    userId: 'AliceTrader',
    fullName: 'Alice Wonder',
    country: 'US',
    dob: '1990-01-01',
    isBanned: false,
    isOnHold: false,
    tradeVolume: 250000,
    completedTrades: 152,
    usernameChanged: false,
    createdAt: sub(now, { years: 2 }).toISOString(),
    lastActive: sub(now, { minutes: 5 }).toISOString(),
    feedbackScore: 98,
    positiveFeedback: 150,
    negativeFeedback: 2,
    avgPaymentTime: 5,
    avgReleaseTime: 3,
    photoURL: 'https://images.unsplash.com/photo-1598625873873-52f9aefd7d9d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHx3b21hbiUyMHNtaWxpbmd8ZW58MHx8fHwxNzcwMDc4NTE3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    badges: ['power', 'verified'],
    securityAnswer: 'dummy',
    securityQuestion: 'dummy',
  },
  {
    id: 'user-002',
    userId: 'BobBuyer',
    fullName: 'Bob Builder',
    country: 'CA',
    dob: '1985-05-10',
    isBanned: false,
    isOnHold: false,
    tradeVolume: 80000,
    completedTrades: 75,
    usernameChanged: true,
    oldUserId: 'BobTheTrader',
    createdAt: sub(now, { months: 18 }).toISOString(),
    lastActive: sub(now, { hours: 1 }).toISOString(),
    feedbackScore: 99.5,
    positiveFeedback: 74,
    negativeFeedback: 0,
    avgPaymentTime: 8,
    avgReleaseTime: 5,
    photoURL: 'https://images.unsplash.com/photo-1619678309629-23bb8fa744cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxtYW4lMjBwcm9mZXNzaW9uYWx8ZW58MHx8fHwxNzcwMTAxNDE4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    badges: ['verified'],
    securityAnswer: 'dummy',
    securityQuestion: 'dummy',
  },
  {
    id: 'user-003',
    userId: 'CharlieP2P',
    fullName: 'Charlie Kumar',
    country: 'IN',
    dob: '1995-08-15',
    isBanned: false,
    isOnHold: false,
    tradeVolume: 12000,
    completedTrades: 30,
    usernameChanged: false,
    createdAt: sub(now, { months: 10 }).toISOString(),
    lastActive: sub(now, { minutes: 25 }).toISOString(),
    feedbackScore: 100,
    positiveFeedback: 30,
    negativeFeedback: 0,
    avgPaymentTime: 10,
    avgReleaseTime: 2,
    photoURL: 'https://images.unsplash.com/photo-1610216705422-caa3fcb6d158?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
    badges: ['verified'],
    securityAnswer: 'dummy',
    securityQuestion: 'dummy',
  },
  {
    id: 'user-004',
    userId: 'DianaSells',
    fullName: 'Diana Okoro',
    country: 'NG',
    dob: '1992-03-22',
    isBanned: false,
    isOnHold: false,
    tradeVolume: 55000,
    completedTrades: 95,
    usernameChanged: false,
    createdAt: sub(now, { years: 1 }).toISOString(),
    lastActive: sub(now, { minutes: 2 }).toISOString(),
    feedbackScore: 97,
    positiveFeedback: 92,
    negativeFeedback: 3,
    avgPaymentTime: 4,
    avgReleaseTime: 4,
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
    badges: ['power'],
    securityAnswer: 'dummy',
    securityQuestion: 'dummy',
  },
  {
    id: 'user-005',
    userId: 'EvaEurope',
    fullName: 'Eva Schmidt',
    country: 'DE',
    dob: '1988-11-30',
    isBanned: false,
    isOnHold: false,
    tradeVolume: 300000,
    completedTrades: 210,
    usernameChanged: false,
    createdAt: sub(now, { years: 3 }).toISOString(),
    lastActive: sub(now, { days: 1, hours: 2 }).toISOString(),
    feedbackScore: 99,
    positiveFeedback: 208,
    negativeFeedback: 2,
    avgPaymentTime: 15,
    avgReleaseTime: 7,
    photoURL: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max',
    badges: ['verified'],
    securityAnswer: 'dummy',
    securityQuestion: 'dummy',
  },
];

const alice = mockUsers.find(u => u.id === 'user-001')!;
const bob = mockUsers.find(u => u.id === 'user-002')!;
const charlie = mockUsers.find(u => u.id === 'user-003')!;
const diana = mockUsers.find(u => u.id === 'user-004')!;
const eva = mockUsers.find(u => u.id === 'user-005')!;


export const mockP2PAds: P2PAd[] = [
  {
    id: 'ad-001',
    publicAdId: 'AD-SELLBTC1',
    userId: alice.id,
    adType: 'sell',
    crypto: 'BTC',
    fiatCurrency: 'USD',
    paymentMethods: ['Zelle', 'Cash App'],
    rateType: 'market',
    ratePercent: 1.5,
    minAmount: 50,
    maxAmount: 500,
    paymentTimeLimit: 30,
    terms: 'Please pay from an account with your own name. No 3rd party payments. Release will be fast.',
    tags: ['No third party'],
    offerLabel: 'Fast and reliable!',
    active: true,
    createdAt: sub(now, { days: 5 }).toISOString(),
    user: {
      userId: alice.userId,
      country: alice.country,
      feedbackScore: alice.feedbackScore,
      completedTrades: alice.completedTrades,
      photoURL: alice.photoURL,
      badges: alice.badges,
      lastActive: alice.lastActive,
    },
  },
  {
    id: 'ad-002',
    publicAdId: 'AD-BUYETH1',
    userId: bob.id,
    adType: 'buy',
    crypto: 'ETH',
    fiatCurrency: 'CAD',
    paymentMethods: ['Interac e-Transfer'],
    rateType: 'market',
    ratePercent: -0.5,
    minAmount: 100,
    maxAmount: 1000,
    paymentTimeLimit: 60,
    terms: 'Looking for fast Interac transfers. I am online most of the day.',
    active: true,
    createdAt: sub(now, { days: 2 }).toISOString(),
    user: {
      userId: bob.userId,
      country: bob.country,
      feedbackScore: bob.feedbackScore,
      completedTrades: bob.completedTrades,
      photoURL: bob.photoURL,
      badges: bob.badges,
      lastActive: bob.lastActive,
    },
  },
  {
    id: 'ad-003',
    publicAdId: 'AD-SELLUSDT1',
    userId: alice.id,
    adType: 'sell',
    crypto: 'USDT',
    fiatCurrency: 'EUR',
    paymentMethods: ['SEPA Transfer', 'Revolut'],
    rateType: 'fixed',
    fixedRate: 0.95,
    minAmount: 200,
    maxAmount: 2000,
    paymentTimeLimit: 60,
    terms: 'SEPA only. Fast release after confirmation.',
    active: true,
    createdAt: sub(now, { hours: 10 }).toISOString(),
    user: {
      userId: alice.userId,
      country: alice.country,
      feedbackScore: alice.feedbackScore,
      completedTrades: alice.completedTrades,
      photoURL: alice.photoURL,
      badges: alice.badges,
      lastActive: alice.lastActive,
    },
  },
  {
    id: 'ad-004',
    publicAdId: 'AD-SELLUSDT2',
    userId: charlie.id,
    adType: 'sell',
    crypto: 'USDT',
    fiatCurrency: 'INR',
    paymentMethods: ['UPI', 'Paytm'],
    rateType: 'market',
    ratePercent: 2.0,
    minAmount: 5000,
    maxAmount: 50000,
    paymentTimeLimit: 30,
    terms: 'Only UPI and Paytm accepted. Fast release guaranteed.',
    tags: ['No third party', 'Invoice accepted'],
    active: true,
    createdAt: sub(now, { days: 1 }).toISOString(),
    user: {
      userId: charlie.userId,
      country: charlie.country,
      feedbackScore: charlie.feedbackScore,
      completedTrades: charlie.completedTrades,
      photoURL: charlie.photoURL,
      badges: charlie.badges,
      lastActive: charlie.lastActive,
    },
  },
  {
    id: 'ad-005',
    publicAdId: 'AD-BUYBTC1',
    userId: diana.id,
    adType: 'buy',
    crypto: 'BTC',
    fiatCurrency: 'NGN',
    paymentMethods: ['Bank Transfer'],
    rateType: 'market',
    ratePercent: 1.0,
    minAmount: 100000,
    maxAmount: 1000000,
    paymentTimeLimit: 45,
    terms: 'Nigerian bank transfer only. Serious sellers please.',
    active: true,
    createdAt: sub(now, { hours: 4 }).toISOString(),
    user: {
      userId: diana.userId,
      country: diana.country,
      feedbackScore: diana.feedbackScore,
      completedTrades: diana.completedTrades,
      photoURL: diana.photoURL,
      badges: diana.badges,
      lastActive: diana.lastActive,
    },
  },
  {
    id: 'ad-006',
    publicAdId: 'AD-SELLETH1',
    userId: eva.id,
    adType: 'sell',
    crypto: 'ETH',
    fiatCurrency: 'EUR',
    paymentMethods: ['SEPA Instant'],
    rateType: 'market',
    ratePercent: 0.8,
    minAmount: 100,
    maxAmount: 1500,
    paymentTimeLimit: 30,
    terms: 'Only SEPA Instant. I am online during EU business hours.',
    active: true,
    createdAt: sub(now, { days: 3 }).toISOString(),
    user: {
      userId: eva.userId,
      country: eva.country,
      feedbackScore: eva.feedbackScore,
      completedTrades: eva.completedTrades,
      photoURL: eva.photoURL,
      badges: eva.badges,
      lastActive: eva.lastActive,
    },
  },
   {
    id: 'ad-007',
    publicAdId: 'AD-SELLLTC1',
    userId: bob.id,
    adType: 'sell',
    crypto: 'LTC',
    fiatCurrency: 'CAD',
    paymentMethods: ['Interac e-Transfer', 'Bank Transfer'],
    rateType: 'fixed',
    fixedRate: 105.50,
    minAmount: 50,
    maxAmount: 800,
    paymentTimeLimit: 30,
    terms: 'Selling LTC for Canadian dollars. Quick response time.',
    active: true,
    createdAt: sub(now, { hours: 20 }).toISOString(),
    user: {
      userId: bob.userId,
      country: bob.country,
      feedbackScore: bob.feedbackScore,
      completedTrades: bob.completedTrades,
      photoURL: bob.photoURL,
      badges: bob.badges,
      lastActive: bob.lastActive,
    },
  },
];


export const mockTrade: Trade | null = null;

export const mockTradeChatMessages: TradeChatMessage[] = [];

export const mockSupportTickets: SupportTicket[] = [];

export const mockFeedbacks: Feedback[] = [];
