import type { User, P2PAd, Trade, TradeChatMessage, SupportTicket, Feedback } from './types';
import { add, sub } from 'date-fns';

const now = new Date();

export const mockUsers: User[] = [
  {
    id: 'user-1',
    userId: 'CryptoKing',
    fullName: 'John Doe',
    dob: '1990-01-15',
    email: 'john@example.com',
    isBanned: false,
    isOnHold: false,
    tradeVolume: '125000.50',
    completedTrades: 150,
    usernameChanged: false,
    createdAt: sub(now, { years: 2 }).toISOString(),
    lastLoginIp: '192.168.1.1',
    feedbackScore: 98,
    accountAge: '2 years',
  },
  {
    id: 'user-2',
    userId: 'SatoshiQueen',
    fullName: 'Jane Smith',
    dob: '1995-05-20',
    email: 'jane@example.com',
    isBanned: false,
    isOnHold: false,
    tradeVolume: '78000.00',
    completedTrades: 89,
    usernameChanged: true,
    oldUserId: 'CryptoJane',
    createdAt: sub(now, { months: 8 }).toISOString(),
    lastLoginIp: '10.0.0.1',
    feedbackScore: 99,
    accountAge: '8 months',
  },
   {
    id: 'user-3',
    userId: 'LTC-Lover',
    fullName: 'Sam Wilson',
    dob: '1988-11-30',
    email: 'sam@example.com',
    isBanned: true,
    isOnHold: false,
    tradeVolume: '500.00',
    completedTrades: 2,
    usernameChanged: false,
    createdAt: sub(now, { days: 10 }).toISOString(),
    lastLoginIp: '172.16.0.1',
    feedbackScore: 50,
    accountAge: '10 days',
  },
];

export const mockP2PAds: P2PAd[] = [
  {
    id: 'ad-1',
    userId: 'user-1',
    adType: 'sell',
    crypto: 'BTC',
    fiat: 'USD',
    paymentMethods: ['Bank Transfer', 'Zelle'],
    rateType: 'market',
    ratePercent: 1.5,
    minAmount: 500,
    maxAmount: 10000,
    terms: 'Serious buyers only. Please provide your real name. No third-party payments. I will release crypto immediately after payment confirmation.',
    active: true,
    createdAt: sub(now, { days: 5 }).toISOString(),
    user: { userId: 'CryptoKing', feedbackScore: 98, completedTrades: 150 },
  },
  {
    id: 'ad-2',
    userId: 'user-2',
    adType: 'sell',
    crypto: 'USDT',
    fiat: 'EUR',
    paymentMethods: ['Revolut', 'SEPA Transfer'],
    rateType: 'fixed',
    fixedRate: 0.99,
    minAmount: 100,
    maxAmount: 2000,
    terms: 'Fast and reliable trader. Only Revolut users from EU. Happy to trade!',
    active: true,
    createdAt: sub(now, { days: 2 }).toISOString(),
    user: { userId: 'SatoshiQueen', feedbackScore: 99, completedTrades: 89 },
  },
    {
    id: 'ad-3',
    userId: 'user-2',
    adType: 'buy',
    crypto: 'ETH',
    fiat: 'GBP',
    paymentMethods: ['PayPal', 'Wise'],
    rateType: 'market',
    ratePercent: -0.5,
    minAmount: 200,
    maxAmount: 1500,
    terms: 'Looking to buy ETH. I pay fast. Please have a verified PayPal account.',
    active: true,
    createdAt: sub(now, { hours: 12 }).toISOString(),
    user: { userId: 'SatoshiQueen', feedbackScore: 99, completedTrades: 89 },
  },
   {
    id: 'ad-4',
    userId: 'user-1',
    adType: 'sell',
    crypto: 'LTC',
    fiat: 'INR',
    paymentMethods: ['UPI', 'Paytm'],
    rateType: 'fixed',
    fixedRate: 8000,
    minAmount: 5000,
    maxAmount: 50000,
    terms: 'Fast trades in INR. UPI preferred. No negotiations.',
    active: true,
    createdAt: sub(now, { days: 1 }).toISOString(),
    user: { userId: 'CryptoKing', feedbackScore: 98, completedTrades: 150 },
  }
];

export const mockTrade: Trade = {
  id: 'trade-1',
  tradeId: 'T-Abc123Xyz',
  buyerId: 'user-2',
  sellerId: 'user-1',
  adId: 'ad-1',
  crypto: 'BTC',
  amount: '0.015',
  fiatAmount: '975.00',
  price: '65000.00',
  status: 'paid',
  expiresAt: add(now, { minutes: 120 }).toISOString(),
  paidAt: sub(now, { minutes: 15 }).toISOString(),
  createdAt: sub(now, { minutes: 25 }).toISOString(),
  buyer: { userId: 'SatoshiQueen' },
  seller: { userId: 'CryptoKing' },
};


export const mockTradeChatMessages: TradeChatMessage[] = [
    {
        id: 'msg-1',
        tradeId: 'trade-1',
        senderId: 'user-2',
        senderUsername: 'SatoshiQueen',
        message: 'Hi, I have opened the trade. Please send payment details.',
        isModerator: false,
        createdAt: sub(now, { minutes: 24 }).toISOString(),
    },
    {
        id: 'msg-2',
        tradeId: 'trade-1',
        senderId: 'user-1',
        senderUsername: 'CryptoKing',
        message: 'Hello! You can pay to Zelle: john@example.com',
        isModerator: false,
        createdAt: sub(now, { minutes: 22 }).toISOString(),
    },
     {
        id: 'msg-3',
        tradeId: 'trade-1',
        senderId: 'user-2',
        senderUsername: 'SatoshiQueen',
        message: 'Payment sent. Please check and release the BTC.',
        isModerator: false,
        createdAt: sub(now, { minutes: 15 }).toISOString(),
    },
    {
        id: 'msg-4',
        tradeId: 'trade-1',
        senderId: 'user-1',
        senderUsername: 'CryptoKing',
        message: 'Payment received. Releasing now. Thanks for the trade!',
        isModerator: false,
        createdAt: sub(now, { minutes: 10 }).toISOString(),
    },
    {
        id: 'msg-5',
        tradeId: 'trade-1',
        senderId: 'user-2',
        senderUsername: 'SatoshiQueen',
        message: 'I am going to report you if you don\'t release my funds right now you scammer!',
        isModerator: false,
        createdAt: sub(now, { minutes: 5 }).toISOString(),
        isHarmful: true,
        harmfulReasoning: "The message contains abusive language ('scammer') and a threat to report, which is considered aggressive and potentially harmful in a trade context.",
    }
];

export const mockSupportTickets: SupportTicket[] = [
  {
    id: 'ticket-1',
    userId: 'user-3',
    email: 'sam@example.com',
    message: "My account is banned and I don't know why. I only made two trades. Please help me, I have funds in my account!",
    status: 'Open',
    createdAt: sub(now, { hours: 2 }).toISOString(),
  },
  {
    id: 'ticket-2',
    userId: 'user-2',
    email: 'jane@example.com',
    message: "I'm having trouble with the 'Generate with AI' button on the ad creation page. It's not working.",
    status: 'In Progress',
    createdAt: sub(now, { days: 1 }).toISOString(),
  },
  {
    id: 'ticket-3',
    userId: 'user-1',
    email: 'john@example.com',
    message: "Just wanted to say this is a great platform! Keep up the good work.",
    status: 'Closed',
    createdAt: sub(now, { days: 3 }).toISOString(),
  },
];

export const mockFeedbacks: Feedback[] = [
    {
        id: 'feedback-1',
        tradeId: 'trade-xyz',
        fromUser: 'user-2',
        toUser: 'user-1',
        rating: 'positive',
        comment: 'Excellent trader! Very fast release and great communication. Highly recommended.',
        createdAt: sub(now, { days: 1 }).toISOString(),
        fromUsername: 'SatoshiQueen',
    },
    {
        id: 'feedback-2',
        tradeId: 'trade-abc',
        fromUser: 'user-3',
        toUser: 'user-1',
        rating: 'negative',
        comment: 'Trader was slow to respond and took a long time to confirm payment. Not a great experience.',
        createdAt: sub(now, { days: 9 }).toISOString(),
        fromUsername: 'LTC-Lover',
    }
];
