export const paymentMethods = [
  "UPI India",
  "IMPS India",
  "NEFT India",
  "RTGS India",
  "BHIM UPI",
  "Bank Transfer USA",
  "Zelle USA",
  "ACH Transfer USA",
  "RTP (Real‑Time Payments) USA",
  "Cash App Balance USA",
  "PayPal Transfer International",
  "Interac e‑Transfer Canada",
  "EFT Canada",
  "Bank Transfer Canada",
  "PIX Brazil",
  "Boleto Bancário Brazil",
  "TED Brazil",
  "DOC Brazil",
  "Mercado Pago Brazil",
  "PicPay Brazil",
  "Nubank Transfer Brazil",
  "Bank Transfer Mexico",
  "SPEI Mexico",
  "OXXO Pay Mexico",
  "Banorte Transfer Mexico",
  "Scotiabank Transfer Mexico",
  "Banco Azteca Pay",
  "Pago Efectivo Peru",
  "Interbank Transfer Peru",
  "Yape Peru",
  "Tunki Peru",
  "Bank Transfer Argentina",
  "Provincia Net Pagos Argentina",
  "Rapipago Argentina",
  "PagoMisCuentas Argentina",
  "Bank Transfer Chile",
  "WebPay Chile",
  "Servipag Chile",
  "TransBank Chile",
  "Bank Transfer Colombia",
  "Nequi Colombia",
  "Daviplata Colombia",
  "PSE Colombia",
  "Efecty Colombia",
  "Baloto Colombia",
  "Bank Transfer Ecuador",
  "DineroMail Ecuador",
  "ServiPagos Ecuador",
  "Bank Transfer Bolivia",
  "Tigo Money Bolivia",
  "Bank Transfer Uruguay",
  "Banco República Uruguay",
  "Bank Transfer Paraguay",
  "Bank Transfer Venezuela",
  "Patria Transfer Venezuela",
  "Banesco Transfer Venezuela",
  "Bank Transfer UK",
  "Faster Payments UK",
  "CHAPS UK",
  "BACS UK",
  "PayID Australia",
  "NPP Australia",
  "Bank Transfer Australia",
  "Osko Australia",
  "Becs Direct Debit Australia",
  "PromptPay Thailand",
  "TrueMoney Thailand",
  "Bank Transfer Thailand",
  "Mobile Banking Thailand",
  "GrabPay Thailand",
  "Bank Transfer Malaysia",
  "DuitNow Malaysia",
  "Boost Malaysia",
  "Touch n Go eWallet Malaysia",
  "ShopeePay Malaysia",
  "Bank Transfer Singapore",
  "FAST Singapore",
  "PayNow Singapore",
  "GrabPay Singapore",
  "Bank Transfer Indonesia",
  "Dana Indonesia",
  "OVO Indonesia",
  "GoPay Indonesia",
  "LinkAja Indonesia",
  "Bank Transfer Philippines",
  "GCash Philippines",
  "PayMaya Philippines",
  "BancNet Philippines",
  "Bank Transfer Japan",
  "PayPay Japan",
  "Line Pay Japan",
  "Bank Transfer South Korea",
  "Kakao Pay Korea",
  "Naver Pay Korea",
  "Toss Korea",
  "Bank Transfer China",
  "Alipay China",
  "WeChat Pay China",
  "UnionPay QuickPass P2P",
  "Bank Transfer Hong Kong",
  "FPS Hong Kong",
  "Octopus Wallet Hong Kong",
  "Bank Transfer UAE",
  "UAE Dirham Bank Transfer",
  "Etisalat Wallet UAE",
  "du Wallet UAE",
  "Bank Transfer Saudi Arabia",
  "SADAD Payment Saudi Arabia",
  "STC Pay Saudi Arabia",
  "Bank Transfer Qatar",
  "Qatar Bank Mobile",
  "Ooredoo Wallet Qatar",
  "Bank Transfer Kuwait",
  "KNET Kuwait",
  "Zain Wallet Kuwait",
  "Bank Transfer Bahrain",
  "BenefitPay Bahrain",
  "Bank Transfer Oman",
  "Omani Bank Transfer",
  "Bank Transfer Egypt",
  "Fawry Egypt",
  "Vodafone Cash Egypt",
  "Bank Transfer Kenya",
  "M‑Pesa Kenya",
  "Airtel Money Kenya",
  "Bank Transfer Tanzania",
  "Tigo Pesa Tanzania",
  "Halopesa Tanzania",
  "Bank Transfer Uganda",
  "MTN Mobile Money Uganda",
  "Airtel Money Uganda",
  "Bank Transfer Nigeria",
  "Paga Nigeria",
  "Bank Transfer Ghana",
  "MTN Mobile Money Ghana",
  "Vodafone Cash Ghana",
  "AirtelTigo Money Ghana",
  "Bank Transfer South Africa",
  "EFT South Africa",
  "Bank Instant EFT South Africa",
  "SnapScan South Africa",
  "Zapper South Africa",
  "Bank Transfer Morocco",
  "Bank Transfer Algeria",
  "CIB Wallet Morocco",
  "Bank Transfer Tunisia",
  "Bank Transfer Senegal",
  "Orange Money Senegal",
  "Wari Senegal",
  "Bank Transfer Ivory Coast",
  "MTN Mobile Money Ivory Coast",
  "Moov Money Ivory Coast",
  "Bank Transfer Democratic Republic of Congo",
  "Airtel Money DRC",
  "Vodacom M‑Pesa DRC",
  "Bank Transfer Zambia",
  "Zoona Zambia",
  "Airtel Money Zambia",
  "Bank Transfer Zimbabwe",
  "EcoCash Zimbabwe",
  "Telecash Zimbabwe",
  "Bank Transfer Rwanda",
  "MTN Mobile Money Rwanda",
  "Airtel Money Rwanda",
  "Bank Transfer Cameroon",
  "MTN Mobile Money Cameroon",
  "Orange Money Cameroon",
  "Bank Transfer Mali",
  "Orange Money Mali",
  "Bank Transfer Niger",
  "Orange Money Niger",
  "Bank Transfer Burkina Faso",
  "MoMo Burkina Faso",
  "Bank Transfer Libya",
  "Libyan Bank Transfer",
  "Bank Transfer Sudan",
  "Bank Transfer Ethiopia",
  "M‑Bank Ethiopia",
  "HelloCash Ethiopia",
  "Bank Transfer Pakistan",
  "Easypaisa Pakistan",
  "JazzCash Pakistan",
  "Bank Transfer Bangladesh",
  "bKash Bangladesh",
  "Nagad Bangladesh",
  "Rocket Bangladesh",
  "Bank Transfer Sri Lanka",
  "eZ Cash Sri Lanka",
  "Bank Transfer Nepal",
  "eSewa Nepal",
  "IME Pay Nepal",
  "Bank Transfer Bhutan",
  "Bank Transfer Maldives",
  "Fonepay Nepal",
  "Bank Transfer Kazakhstan",
  "Halyk Bank Transfer Kazakhstan",
  "Kaspi Wallet Kazakhstan",
  "Bank Transfer Uzbekistan",
  "Bank Transfer Azerbaijan",
  "MilliONAZE Wallet Azerbaijan",
  "Bank Transfer Armenia",
  "Idram Armenia",
  "Bank Transfer Georgia",
  "Bank Transfer Turkey",
  "Papara Turkey",
  "Ininal Turkey",
  "Bank Transfer Israel",
  "PayBox Israel",
  "Bit Wallet Israel",
  "Bank Transfer Palestine",
  "Jawwal Wallet Palestine",
  "Bank Transfer Jordan",
  "eFAWATEERcom Jordan",
  "Bank Transfer Lebanon",
  "Bank Transfer Cyprus",
  "Bank Transfer Greece",
  "Bank Transfer France",
  "Bank Transfer Germany",
  "Sofort Germany",
  "Giropay Germany",
  "SEPA Instant Europe",
  "iDEAL Netherlands",
  "Bancontact Belgium",
  "Bank Transfer Belgium",
  "Bank Transfer Italy",
  "Postepay Italy",
  "Satispay Italy",
  "Bank Transfer Spain",
  "Bizum Spain",
  "Bank Transfer Portugal",
  "Multibanco Portugal",
  "Bank Transfer Ireland",
  "Bank Transfer Austria",
  "Bank Transfer Switzerland",
  "Twint Switzerland",
  "Bank Transfer Norway",
  "VIPPS Norway",
  "Bank Transfer Sweden",
  "Swish Sweden",
  "Bank Transfer Denmark",
  "MobilePay Denmark",
  "Bank Transfer Finland",
  "Siirto Finland",
  "Bank Transfer Poland",
  "BLIK Poland",
  "Bank Transfer Czech Republic",
  "Bank Transfer Slovakia",
  "Bank Transfer Hungary",
  "Bank Transfer Romania",
  "Bank Transfer Bulgaria",
  "Bank Transfer Croatia",
  "Bank Transfer Serbia",
  "Bank Transfer Slovenia",
  "Bank Transfer Bosnia",
  "Bank Transfer Montenegro",
  "Bank Transfer Macedonia",
  "Bank Transfer Albania",
  "Bank Transfer Belarus",
  "Bank Transfer Ukraine",
  "Privat24 Ukraine",
  "Bank Transfer Latvia",
  "Bank Transfer Lithuania",
  "Bank Transfer Estonia",
  "Bank Transfer Iceland",
  "Bank Transfer Luxembourg",
  "Bank Transfer Monaco",
  "Bank Transfer Liechtenstein",
  "Bank Transfer Malta",
  "Bank Transfer San Marino",
  "Bank Transfer Andorra",
  "Bank Transfer Vatican City",
  "Bank Transfer Greenland",
  "Bank Transfer Faroe Islands",
  "Bank Transfer Armenia",
  "Bank Transfer Georgia",
  "Bank Transfer Azerbaijan",
  "Bank Transfer Mongolia",
  "Bank Transfer South Korea QR",
  "Bank Transfer Japan QR",
  "Bank Transfer Vietnam",
  "MoMo Vietnam",
  "ZaloPay Vietnam",
  "Bank Transfer Cambodia",
  "Wing Cambodia",
  "TrueMoney Cambodia",
  "Bank Transfer Laos",
  "BCEL OnePay Laos",
  "Bank Transfer Myanmar",
  "WavePay Myanmar",
  "KBZ Pay Myanmar",
  "Bank Transfer Thailand QR PromptPay",
  "Bank Transfer Taiwan",
  "JKoPay Taiwan",
  "Bank Transfer Hong Kong QR",
  "Bank Transfer Macao",
  "Bank Transfer Brunei",
  "Baiduri Bank Transfer",
  "Bank Transfer Nepal QR",
  "Bank Transfer Bhutan QR",
  "Bank Transfer Sri Lanka QR",
  "Bank Transfer Maldives QR",
  "Bank Transfer Pakistan QR",
  "Bank Transfer Bangladesh QR",
  "Bank Transfer Africa Regional QR",
  "Bank Transfer Middle East Regional QR",
  "Cash In Hand Global",
  "Cash Meeting in Person Global",
  "Gift Card Amazon",
  "Gift Card Google Play",
  "Gift Card iTunes",
  "Gift Card Steam Wallet",
  "Gift Card Walmart",
  "Gift Card Target",
  "Gift Card Best Buy",
  "Gift Card Xbox",
  "Gift Card Playstation",
  "Gift Card Nintendo",
  "Gift Card Visa Prepaid",
  "Gift Card Mastercard Prepaid",
  "Gift Card Universal",
  "Gift Card Crypto Specific (e.g., Bitit, MoonPay Vouchers)",
  "Voucher Paysafecard",
  "Voucher Neosurf",
  "Voucher Prepaid Wallet",
  "Voucher SuperGift",
  "Voucher Retail Exchange",
  "QR Wallet Pay Global",
  "QR Code Bank Transfer",
  "QR Code Mobile Money",
  "QR Pay US/Global",
  "Agent Assisted Cash Deposit",
  "Postal Money Order Global",
  "Western Union P2P",
  "MoneyGram P2P",
  "Ria Transfer P2P",
  "Remitly Cash Out",
  "WorldRemit Cash Out",
  "Xoom Cash Pickup",
  "Bank Counter Cash Deposit",
  "ATM Deposit Transfer",
  "Community Bank Transfer",
  "Cooperative Bank Transfer",
  "Credit Union Transfer",
  "Microfinance Wallets",
  "Fintech Wallet Transfers",
  "Digital Bank Transfers",
  "E‑money Wallets",
  "Virtual Account Transfers",
  "API Bank Transfers",
  "P2P Bank Token Pay",
  "Bank Reference Number Transfer",
  "Gig Worker Wallets",
  "Freelancer Payment Wallets",
  "NGO Aid Wallet Transfers",
  "Student Pay Wallets",
  "Salary Disbursement Wallet Transfers",
  "Merchant Settlement Wallet",
  "Local QR Pay Networks",
  "Neighborhood Cash Exchange",
  "Trade Office Cash Settlement",
  "Peer Ledger Transfer",
  "Multilingual Payment Exchange",
  "Crypto Voucher Exchange",
  "Retailer Cash Exchange",
  "Local Biz Wallet Exchange",
  "Cooperative Wallet Pay",
  "P2P Telecom Billing",
  "P2P Utility Bill Credit Pay",
  "Charity Wallet P2P",
  "NGO Wallet Pay",
  "Government P2P Wallets",
  "Infrastructure Wallet Pay",
  "Campus Payment Wallets"
];
