
export const bankTransfers: string[] = [
    "Bank Transfer",
    "SEPA Transfer",
    "SWIFT",
    "UPI (Unified Payments Interface)",
    "IMPS (Immediate Payment Service)",
    "NEFT (National Electronic Funds Transfer)",
    "RTGS (Real-Time Gross Settlement)",
    "Interac e-Transfer",
    "PayID",
    "Osko",
    "Pix (Brazil)",
    "SPEI (Mexico)",
    "CoDi (Mexico)",
    "PSE (Colombia)",
    "Transfiya (Colombia)",
    "FPS (Faster Payment System)",
    "Domestic wire transfer",
    "International wire transfer",
    "ACH transfer",
    "EFT (Electronic Funds Transfer)",
    "Direct debit",
    "iDEAL",
    "Bancontact",
    "Giropay",
    "EPS",
    "Sofort",
    "PesaLink",
    "BLIK",
    "Przelewy24",
    "MB WAY",
    "Bizum",
    "Swish",
    "TWINT",
    "Paylib",
    "and all major international and local banks..."
];

export const onlineWallets: string[] = [
    "Wise (formerly TransferWise)",
    "Revolut",
    "PayPal",
    "Skrill",
    "Neteller",
    "Payoneer",
    "Zelle",
    "Venmo",
    "Cash App",
    "Google Pay",
    "Apple Pay",
    "Alipay",
    "WeChat Pay",
    "Mercado Pago",
    "PicPay",
    "AstroPay",
    "Advcash",
    "Perfect Money",
    "Payeer",
    "AirTM",
    "Uphold",
    "Paybis",
    "QIWI",
    "YooMoney (formerly Yandex.Money)",
    "WebMoney",
    "PayU",
    "Verse",
    "Lydia",
    "PostePay",
    "SATISPAY",
    "Trustly",
    "Klarna",
    "Stripe",
    "Binance Pay",
    "Crypto.com Pay",
    "Coinbase Commerce",
    "BitPay",
    "Paxful",
    "Remitly",
    "WorldRemit",
    "Xoom"
];

export const mobileMoney: string[] = [
    "M-Pesa",
    "Airtel Money",
    "MTN Mobile Money",
    "Orange Money",
    "Vodafone Cash",
    "Tigo Money",
    "MoMo",
    "ZaloPay",
    "ViettelPay",
    "Paytm",
    "PhonePe",
    "GCash",
    "PayMaya",
    "GrabPay",
    "GoPay",
    "OVO",
    "DANA",
    "LinkAja",
    "Touch 'n Go eWallet",
    "Boost",
    "Easypaisa",
    "JazzCash",
    "bKash",
    "Nagad",
    "Rocket",
    "Khalti",
    "eSewa",
    "Wave Money",
    "KBZPay",
    "Tigo Pesa",
    "Halopesa",
    "Azampay",
    "Chipper Cash",
    "JumiaPay"
];

export const cashPayments: string[] = [
    "Cash deposit to bank",
    "Cash in person",
    "Western Union",
    "MoneyGram",
    "Ria Money Transfer",
    "Cash by mail",
    "Postal order",
    "Bank draft",
    "Cashier's check"
];

export const giftCardPaymentMethods: string[] = [
    "Amazon Gift Card",
    "iTunes Gift Card",
    "Google Play Gift Card",
    "Steam Gift Card",
    "PlayStation Network Gift Card",
    "Xbox Gift Card",
    "Nintendo eShop Gift Card",
    "eBay Gift Card",
    "Walmart Gift Card",
    "Target Gift Card",
    "Best Buy Gift Card",
    "Sephora Gift Card",
    "Starbucks Gift Card",
    "Netflix Gift Card",
    "Spotify Gift Card",
    "Uber Gift Card",
    "Lyft Gift Card",
    "Airbnb Gift Card",
    "Hotels.com Gift Card",
    "Delta Air Lines Gift Card",
    "Southwest Airlines Gift Card",
    "American Airlines Gift Card",
    "Vanilla Visa/Mastercard Gift Card",
    "Razer Gold Gift Card",
    "Roblox Gift Card",
    "Fortnite V-Bucks Gift Card",
    "Apple Gift Card"
];
